[package]
name = "wasm-rs"
version = "0.1.0"
authors = ["kgtkr <kgtkr.jp@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
leb128 = "0.2"
nom = "5.0.1"

[dev-dependencies]
proptest-derive = "0.1"
proptest = "0.9.4"