[package]
name = "cl8w-on-wasm-bin"
version = "0.1.0"
authors = ["kgtkr <kgtkr.jp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-rs = { path = "../" }
maplit = "1.0.2"