name: main

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          git submodule init
          git submodule update
      - run: |
          git clone --recursive https://github.com/WebAssembly/wabt
          cd wabt
          git checkout 1.0.12
          make
          echo ::add-path::$PWD/bin
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: ./init.sh
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          override: true
      - run: cargo test
